
name: Check Broken Links

on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    # Define job-level variables here for easy maintenance
    env:
      PREPROCESS: "preprocess.sh"
      LYCHEE_REPORT: "broken-links.md"
      DOCBOOK_XSL_PATH: "/usr/share/xml/docbook/stylesheet/docbook-xsl-ns/xhtml/docbook.xsl"

    steps:
      - uses: actions/checkout@v5

      - name: Save PR Number
        if: always()
        run: echo "${{ github.event.number }}" > pr_number.txt

      # Maybe fetch that from an external source?
      - name: Create Lychee config
        run: |
          cat > lychee.toml << EOF
          # Verbose program output
          # Accepts log level: "error", "warn", "info", "debug", "trace"
          verbose = "debug"
          # Path to summary output file.
          output = "broken-links.md"
          # Preprocess input files
          preprocess = { command = "preprocess.sh" }
          # Only check local files
          offline = true
          #
          exclude = [ "mailto:.*"]
          #
          exclude_path = [
              "(^|/)test/",   # skip directories named "test"
              "(^|/)build/",  # skip directories named "build"
              "(^|/)l10n/",   # skip l10n directories
          ]
          EOF

      - name: Create preprocess.sh
        run: |
          cat > preprocess.sh << EOF
          #!/usr/bin/env bash
          # Use 'set -e' to exit on any error in the conversion process
          set -e

          case "$1" in
            *.adoc|*.asciidoc)
                asciidoctor -a stylesheet! "$1" -o -
                ;;

            *.xml)
                # It's quick and doesn't requires daps, maybe there is even an easier way:
                xmllint --noent "$1" | pandoc --from=docbook --to=html -
                ;;

            *.html|*.htm)
              # identity function, output input without changes
              exec cat
          esac
          EOF

      - name: Find files
        id: find_files
        run: |
          # Find the files (excluding schemas.xml) and join them into a single string
          FILES=$(find . -type f \( -name "*.adoc" -o -name "*.xml" \) \
              -not -name "schemas.xml" \
             | tr '\n' ' ')
          echo "file_list=$FILES" >> $GITHUB_OUTPUT

      - name: Check links
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: lycheeverse/lychee-action@v2
        with:
          # Remap live URLs to build directory because the links are potentially not live (not yet on main/master)
          args: |
            ${{ steps.find_files.outputs.file_list }}
          fail: true
          output: broken-links.md

      - name: Upload Broken Links Artifacts
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: link-check-results
          path: |
            broken-links.md
            pr_number.txt
