---
name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: 4
        required: false
      tag:
        description: "Tag"
        required: true

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tag }}"
